name: upnp
version: 2.0.1
description: Universal Plugin and Play Host/Client
#homepage: https://github.com/SpinlockLabs/upnp.dart
homepage: https://github.com/dmckminard/upnp
dependencies:
  xml: ^5.2.0
  crypto: ^3.0.1
environment:
  sdk: ">=2.12.0 <3.0.0"

